$(document).ready(function(){
$("body").css("display","none");
$("body").fadeIn("slow");
$("a[target],a[href*='javascript'],a.lightbox-processed,a[href*='#']").addClass("speciallinks");
$("a:not(.speciallinks)").click(function(){
$("body").fadeOut("slow");
$("object,embed").css("visibility","hidden");
});
});